### ISSUE TITLE
Publish WPF Desktop App not possible

### ISSUE THREAD

**Issue by BennyBread** [microsoft/CsWin32#1188]
I'm getting the same error when trying to publisch my wpf application with this settings:
net8.0-windows
win-x64
framework dependend.

this ist the logfile produced:

```
22.04.2024 19:10:22
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

===================
```

The minimal build output is more talkactive:

```
...
4>------ Publish started: Project: <APP>.Gui, Configuration: Release Any CPU ------
4>Determining projects to restore...
4>Restored D:\<MyProject>\<APP>.Common\<APP>.Common.csproj (in 870 ms).
4>Restored D:\<MyProject>\<APP>.Database\<APP>.Database.csproj (in 936 ms).
4>1 of 3 projects are up-to-date for restore.
4>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,CA1416,1701,1702,2008 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:8 /define:TRACE;RELEASE;NET;NET8_0;NETCOREAPP;WINDOWS;WINDOWS7_0;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NET7_0_OR_GREATER;NET8_0_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER;WINDOWS7_0_OR_GREATER /errorendlocation /preferreduilang:en-US /highentropyva+ /nullable:enable /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\Accessibility.dll" /reference:D:\<MyProject>\<APP>.Common\bin\Release\net8.0-windows\<APP>.Common.dll /reference:D:\<MyProject>\<APP>.Database\bin\Release\net8.0-windows\<APP>.Database.dll /reference:C:\Users\<USER>\.nuget\packages\castle.core\5.1.1\lib\net6.0\Castle.Core.dll /reference:C:\Users\<USER>\.nuget\packages\controlzex\4.4.0\lib\netcoreapp3.1\ControlzEx.dll /reference:C:\Users\<USER>\.nuget\packages\mahapps.metro\2.4.10\lib\netcoreapp3.1\MahApps.Metro.dll /reference:C:\Users\<USER>\.nuget\packages\mahapps.metro.iconpacks.material\4.11.0\lib\net5.0-windows7.0\MahApps.Metro.IconPacks.Core.dll /reference:C:\Users\<USER>\.nuget\packages\mahapps.metro.iconpacks.fontawesome\4.11.0\lib\net5.0-windows7.0\MahApps.Metro.IconPacks.FontAwesome.dll /reference:C:\Users\<USER>\.nuget\packages\mahapps.metro.iconpacks.material\4.11.0\lib\net5.0-windows7.0\MahApps.Metro.IconPacks.Material.dll /reference:C:\Users\<USER>\.nuget\packages\materialdesigncolors\3.0.0\lib\net7.0\MaterialDesignColors.dll /reference:C:\Users\<USER>\.nuget\packages\materialdesignthemes\5.0.0\lib\net7.0\MaterialDesignThemes.Wpf.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\Microsoft.CSharp.dll" /reference:C:\Users\<USER>\.nuget\packages\microsoft.data.sqlite.core\8.0.3\lib\net8.0\Microsoft.Data.Sqlite.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.entityframeworkcore.abstractions\8.0.3\lib\net8.0\Microsoft.EntityFrameworkCore.Abstractions.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.entityframeworkcore\8.0.3\lib\net8.0\Microsoft.EntityFrameworkCore.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.entityframeworkcore.proxies\8.0.3\lib\net8.0\Microsoft.EntityFrameworkCore.Proxies.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.entityframeworkcore.relational\8.0.3\lib\net8.0\Microsoft.EntityFrameworkCore.Relational.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.entityframeworkcore.sqlite.core\8.0.3\lib\net8.0\Microsoft.EntityFrameworkCore.Sqlite.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.caching.abstractions\8.0.0\lib\net8.0\Microsoft.Extensions.Caching.Abstractions.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.caching.memory\8.0.0\lib\net8.0\Microsoft.Extensions.Caching.Memory.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.configuration.abstractions\8.0.0\lib\net8.0\Microsoft.Extensions.Configuration.Abstractions.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\8.0.1\lib\net8.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.0\lib\net8.0\Microsoft.Extensions.DependencyInjection.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.dependencymodel\8.0.0\lib\net8.0\Microsoft.Extensions.DependencyModel.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.logging.abstractions\8.0.0\lib\net8.0\Microsoft.Extensions.Logging.Abstractions.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.logging\8.0.0\lib\net8.0\Microsoft.Extensions.Logging.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.options\8.0.0\lib\net8.0\Microsoft.Extensions.Options.dll /reference:C:\Users\<USER>\.nuget\packages\microsoft.extensions.primitives\8.0.0\lib\net8.0\Microsoft.Extensions.Primitives.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\Microsoft.VisualBasic.Core.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\Microsoft.VisualBasic.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\Microsoft.Win32.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\Microsoft.Win32.Registry.AccessControl.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\Microsoft.Win32.Registry.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\Microsoft.Win32.SystemEvents.dll" /reference:C:\Users\<USER>\.nuget\packages\microsoft.xaml.behaviors.wpf\1.1.39\lib\net5.0-windows7.0\Microsoft.Xaml.Behaviors.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\mscorlib.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\netstandard.dll" /reference:C:\Users\<USER>\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0\Newtonsoft.Json.dll /reference:C:\Users\<USER>\.nuget\packages\nhotkey\3.0.0\lib\net6.0-windows7.0\NHotkey.dll /reference:C:\Users\<USER>\.nuget\packages\nhotkey.wpf\3.0.0\lib\net6.0-windows7.0\NHotkey.Wpf.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationCore.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationFramework.Aero.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationFramework.Aero2.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationFramework.AeroLite.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationFramework.Classic.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationFramework.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationFramework.Luna.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationFramework.Royale.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\PresentationUI.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\ReachFramework.dll" /reference:C:\Users\<USER>\.nuget\packages\sqlitepclraw.bundle_e_sqlite3\2.1.6\lib\netstandard2.0\SQLitePCLRaw.batteries_v2.dll /reference:C:\Users\<USER>\.nuget\packages\sqlitepclraw.core\2.1.6\lib\netstandard2.0\SQLitePCLRaw.core.dll /reference:C:\Users\<USER>\.nuget\packages\sqlitepclraw.provider.e_sqlite3\2.1.6\lib\net6.0-windows7.0\SQLitePCLRaw.provider.e_sqlite3.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.AppContext.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Buffers.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.CodeDom.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Collections.Concurrent.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Collections.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Collections.Immutable.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Collections.NonGeneric.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Collections.Specialized.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ComponentModel.Annotations.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ComponentModel.DataAnnotations.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ComponentModel.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ComponentModel.EventBasedAsync.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ComponentModel.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ComponentModel.TypeConverter.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Configuration.ConfigurationManager.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Configuration.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Console.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Core.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Data.Common.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Data.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.Contracts.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.Debug.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.DiagnosticSource.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.EventLog.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.FileVersionInfo.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.PerformanceCounter.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.Process.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.StackTrace.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.TextWriterTraceListener.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.Tools.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.TraceSource.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.DirectoryServices.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Drawing.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Drawing.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Dynamic.Runtime.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Formats.Asn1.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Formats.Tar.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Globalization.Calendars.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Globalization.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Globalization.Extensions.dll" /reference:C:\Users\<USER>\.nuget\packages\system.io.abstractions\21.0.2\lib\net8.0\System.IO.Abstractions.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.Compression.Brotli.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.Compression.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.Compression.FileSystem.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.Compression.ZipFile.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.FileSystem.AccessControl.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.FileSystem.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.FileSystem.DriveInfo.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.FileSystem.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.FileSystem.Watcher.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.IsolatedStorage.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.MemoryMappedFiles.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.IO.Packaging.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.Pipes.AccessControl.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.Pipes.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.IO.UnmanagedMemoryStream.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Linq.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Linq.Expressions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Linq.Parallel.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Linq.Queryable.dll" /reference:C:\Users\<USER>\.nuget\packages\system.management\8.0.0\lib\net8.0\System.Management.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Memory.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Http.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Http.Json.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.HttpListener.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Mail.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.NameResolution.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.NetworkInformation.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Ping.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Quic.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Requests.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Security.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.ServicePoint.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.Sockets.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.WebClient.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.WebHeaderCollection.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.WebProxy.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.WebSockets.Client.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Net.WebSockets.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Numerics.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Numerics.Vectors.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ObjectModel.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Printing.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.DispatchProxy.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.Emit.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.Emit.ILGeneration.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.Emit.Lightweight.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.Metadata.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Reflection.TypeExtensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Resources.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Resources.Reader.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Resources.ResourceManager.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Resources.Writer.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.CompilerServices.Unsafe.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.CompilerServices.VisualC.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Handles.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.InteropServices.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.InteropServices.JavaScript.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.InteropServices.RuntimeInformation.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Intrinsics.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Loader.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Numerics.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Serialization.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Serialization.Formatters.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Serialization.Json.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Serialization.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Runtime.Serialization.Xml.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.AccessControl.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Claims.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.Algorithms.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.Cng.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.Csp.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.Encoding.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.OpenSsl.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.Pkcs.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.ProtectedData.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.X509Certificates.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Security.Cryptography.Xml.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Security.Permissions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Principal.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.Principal.Windows.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Security.SecureString.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ServiceModel.Web.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ServiceProcess.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Text.Encoding.CodePages.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Text.Encoding.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Text.Encoding.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Text.Encodings.Web.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Text.Json.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Text.RegularExpressions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Threading.AccessControl.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Channels.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Overlapped.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Tasks.Dataflow.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Tasks.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Tasks.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Tasks.Parallel.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Thread.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.ThreadPool.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Threading.Timer.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Transactions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Transactions.Local.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.ValueTuple.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Web.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Web.HttpUtility.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Windows.Controls.Ribbon.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Windows.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Windows.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Windows.Input.Manipulations.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Windows.Presentation.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\System.Xaml.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.Linq.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.ReaderWriter.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.Serialization.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.XDocument.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.XmlDocument.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.XmlSerializer.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.XPath.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\ref\net8.0\System.Xml.XPath.XDocument.dll" /reference:C:\Users\<USER>\.nuget\packages\testableio.system.io.abstractions\21.0.2\lib\net8.0\TestableIO.System.IO.Abstractions.dll /reference:C:\Users\<USER>\.nuget\packages\testableio.system.io.abstractions.wrappers\21.0.2\lib\net8.0\TestableIO.System.IO.Abstractions.Wrappers.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\UIAutomationClient.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\UIAutomationClientSideProviders.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\UIAutomationProvider.dll" /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\UIAutomationTypes.dll" /reference:C:\Users\<USER>\.nuget\packages\unity.abstractions\5.11.7\lib\netcoreapp3.0\Unity.Abstractions.dll /reference:C:\Users\<USER>\.nuget\packages\unity.container\5.11.11\lib\netcoreapp3.0\Unity.Container.dll /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.3\ref\net8.0\WindowsBase.dll" /debug- /debug:portable /filealign:512 /optimize+ /out:obj\Release\net8.0-windows\win-x64\AtcPostProcessor.Gui.dll /refout:obj\Release\net8.0-windows\win-x64\refint\AtcPostProcessor.Gui.dll /target:winexe /warnaserror- /utf8output /deterministic+ /langversion:10.0 /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\About\AboutControl.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Home\HomeView.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\MainWindow.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Sequences\SequenceEditControl.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Settings\SettingsView.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\SplashScreen.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Steps\StepEditControl.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Tasks\TasksView.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Teach\TeachView.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Teach\_PointTeachControl.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\App.g.cs /embed:D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\GeneratedInternalTypeHelper.g.cs /embed:"obj\Release\net8.0-windows\win-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" /embed:obj\Release\net8.0-windows\win-x64\<APP>.Gui_5nsy0oqy_wpftmp.GlobalUsings.g.cs /analyzerconfig:obj\Release\net8.0-windows\win-x64\<APP>.Gui_5nsy0oqy_wpftmp.GeneratedMSBuildEditorConfig.editorconfig /analyzerconfig:"C:\Program Files\dotnet\sdk\8.0.202\Sdks\Microsoft.NET.Sdk\analyzers\build\config\analysislevel_8_default.globalconfig" /analyzer:"C:\Program Files\dotnet\sdk\8.0.202\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll" /analyzer:"C:\Program Files\dotnet\sdk\8.0.202\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll" /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.codeanalysis.analyzers\3.3.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.codeanalysis.analyzers\3.3.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.entityframeworkcore.analyzers\8.0.3\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.extensions.logging.abstractions\8.0.0\analyzers\dotnet\roslyn4.4\cs\Microsoft.Extensions.Logging.Generators.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.extensions.options\8.0.0\analyzers\dotnet\roslyn4.4\cs\Microsoft.Extensions.Options.SourceGeneration.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.windows.cswin32\0.3.49-beta\analyzers\cs\MessagePack.Annotations.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.windows.cswin32\0.3.49-beta\analyzers\cs\MessagePack.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.windows.cswin32\0.3.49-beta\analyzers\cs\Microsoft.Bcl.AsyncInterfaces.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.windows.cswin32\0.3.49-beta\analyzers\cs\Microsoft.Windows.CsWin32.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.windows.cswin32\0.3.49-beta\analyzers\cs\Microsoft.Windows.SDK.Win32Docs.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.windows.cswin32\0.3.49-beta\analyzers\cs\System.Text.Encodings.Web.dll /analyzer:C:\Users\<USER>\.nuget\packages\microsoft.windows.cswin32\0.3.49-beta\analyzers\cs\System.Text.Json.dll /analyzer:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\analyzers/dotnet/cs/Microsoft.Interop.ComInterfaceGenerator.dll" /analyzer:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll" /analyzer:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll" /analyzer:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\analyzers/dotnet/cs/Microsoft.Interop.SourceGeneration.dll" /analyzer:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll" /analyzer:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.3\analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll" /analyzer:C:\Users\<USER>\.nuget\packages\system.text.json\8.0.0\analyzers\dotnet\roslyn4.4\cs\System.Text.Json.SourceGeneration.dll App.xaml.cs AssemblyInfo.cs Communication\EstlcamCommunication.cs Infrastructure\BindingProxy.cs Infrastructure\CompositionRoot\DependencyResolver.cs Infrastructure\ItemHelper.cs Infrastructure\Startup\IAsyncStartupStep.cs Infrastructure\Startup\IStartupStep.cs Infrastructure\Startup\StartupService.cs "Infrastructure\Startup\Steps\1 EnsureDatabaseDirectory.cs" "Infrastructure\Startup\Steps\2 InitDatabase.cs" "Infrastructure\Startup\Steps\3 InitSettings.cs" Infrastructure\Startup\Steps\LoadStepData.cs Infrastructure\ToolFunctions.cs Infrastructure\Utilities\Automation.cs Infrastructure\Utilities\SendKeys.cs Windows\About\AboutControl.xaml.cs Windows\About\AboutViewModel.cs Windows\Home\HomeView.xaml.cs Windows\MainViewModel.cs Windows\MainWindow.xaml.cs Windows\Sequences\SequenceEditControl.xaml.cs Windows\Settings\SettingsView.xaml.cs Windows\SplashScreen.xaml.cs Windows\Steps\StepEditControl.xaml.cs Windows\Steps\StepsViewModel.cs Windows\Tasks\TasksView.xaml.cs Windows\Tasks\TasksViewModel.cs Windows\Teach\TeachView.xaml.cs Windows\Teach\TeachViewModel.cs Windows\Teach\_PointTeachControl.xaml.cs "..\Solution Items\SharedAssemblyVersionInfo.cs" "..\Solution Items\SharedAssemblyInfo.cs" D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\About\AboutControl.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Home\HomeView.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\MainWindow.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Sequences\SequenceEditControl.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Settings\SettingsView.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\SplashScreen.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Steps\StepEditControl.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Tasks\TasksView.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Teach\TeachView.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\Windows\Teach\_PointTeachControl.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\App.g.cs D:\<MyProject>\<APP>.Gui\obj\Release\net8.0-windows\win-x64\GeneratedInternalTypeHelper.g.cs "obj\Release\net8.0-windows\win-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" obj\Release\net8.0-windows\win-x64\<APP>.Gui_5nsy0oqy_wpftmp.GlobalUsings.g.cs /warnaserror+:NU1605,SYSLIB0011
4>The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'HWND' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'HWND' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'HWND' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'HWND' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'HWND' could not be found (are you missing a using directive or an assembly reference?)
4>The type or namespace name 'HWND' could not be found (are you missing a using directive or an assembly reference?)

========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 19:10 and took 11,271 seconds ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
========== Publish completed at 19:10 and took 11,272 seconds ==========

> Build started at 19:10 and took 8.863 seconds
```

Seems the runtime generated Win32 pinvoke classes / files are not found..
ps: sorry for the big and long posting.

_Originally posted by @BennyBread in https://github.com/microsoft/CsWin32/issues/560#issuecomment-2070310627_

**Comment by BennyBread** [comment]
I have created a small sample app in this repo to reproduce the issue:  [WpfCsWin32PublishApp](https://github.com/BennyBread/WpfCsWin32PublishApp)

I am NOT trying to publish an Appx Package, just a simple publish to folder..

**Comment by AArnott** [comment]
@mslukewest is this an area you own as well?

**Comment by riverar** [comment]
Am seeing same issue across WPF and WAProj (Packaging Project) too. It's like the Roslyn source generators aren't running at all.

**Comment by AArnott** [comment]
Yes, that's what's happening IIRC. At least for wapproj packaging, it had some really weird way of building the referenced project that blocked source generators from running. So ultimately, this isn't a CsWin32 bug at all -- It's just that Cswin32 is the first source generator used by some of these users so it got the blame. :|

**Comment by riverar** [comment]
Interestingly, publish outside VS IDE (e.g., MSBuild with VS and dotnet SDK) work fine. Starting to wonder if it's a VS IDE bug?

**Comment by MSLukeWest** [comment]
@AArnott No, since this repro doesn't involve wapproj it's not something that's owned by my team.  The build portion would be the dotnet sdk team.

However, I can tell you that the best way of investigating the root cause of an issue that repros when doing a publish in the IDE but not a 'dotnet publish'.  I recommend installing this extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022, then turn on build logging and do the publish.  You'll likely see that the 'publish' step is broken into a restore build and a publish build (based on what's in the publish profile), and you'll have a .binlog file for the failing publish.

**Comment by BennyBread** [comment]
Thanks to mention "dotnet publish". I just managed to publish my real project. Yay!!  🥇 💯 

The sample project also publishes without problems using this command line:

`dotnet publish WpfCsWin32PublishApp.sln -f net8.0-windows -r win-x64 -o .\publish -p:PublishSingleFile=true --no-self-contained -p:PublishReadyToRun=true`

But it would of course be very desirable for most users if this would also work via VS IDE... ;-)

**Comment by riverar** [comment]
Removing `AnyCPU` from `<Platforms>` (or adding an explicit `<Platforms>` with non-AnyCPU targets) seems to alleviate the issue. So it's some weird handling--waves hands--around there.

**Comment by riverar** [comment]
Here's a repro that includes wapproj.
[CsWin32WaprojDeployRepro.zip](https://github.com/user-attachments/files/15571552/CsWin32WaprojDeployRepro.zip)

1. Select the packaging project
2. Project > Publish > Create app packages
3. Complete the wizard (Sideloading > Skip signing > x86 + x64 + arm64 > Installer URI https://example.org > Create
4. Observe error in Error List / Output window:

```
The name 'Windows' does not exist in the current context [...]
X:\CsWin32DeployRepro\WpfApp\MainWindow.xaml.cs	
```

**Comment by riverar** [comment]
@MSLukeWest Is this something you can help investigate? I tried filing a VS Community bug but the site is broken and isn't allowing new submissions.

**Comment by riverar** [comment]
Hmm, this is getting passed to CSC which doesn't look right

```
/analyzer:C:\Users\Rafael\.nuget\packages\microsoft.windows.cswin32\0.3.106\analyzers\cs\MessagePack.Annotations.dll /analyzer:C:\Users\Rafael\.nuget\packages\microsoft.windows.cswin32\0.3.106\analyzers\cs\MessagePack.dll /analyzer:C:\Users\Rafael\.nuget\packages\microsoft.windows.cswin32\0.3.106\analyzers\cs\Microsoft.Bcl.AsyncInterfaces.dll /analyzer:C:\Users\Rafael\.nuget\packages\microsoft.windows.cswin32\0.3.106\analyzers\cs\Microsoft.Windows.CsWin32.dll /analyzer:C:\Users\Rafael\.nuget\packages\microsoft.windows.cswin32\0.3.106\analyzers\cs\Microsoft.Windows.SDK.Win32Docs.dll /analyzer:C:\Users\Rafael\.nuget\packages\microsoft.windows.cswin32\0.3.106\analyzers\cs\System.Text.Encodings.Web.dll /analyzer:C:\Users\Rafael\.nuget\packages\microsoft.windows.cswin32\0.3.106\analyzers\cs\System.Text.Json.dll
```

**Comment by AArnott** [comment]
@riverar I already have started an email thread with a couple folks. Waiting on responses.

**Comment by AArnott** [comment]
> Here's a repro that includes wapproj.
[CsWin32WaprojDeployRepro.zip](https://github.com/user-attachments/files/15571552/CsWin32WaprojDeployRepro.zip)

@riverar your repro zip crashes 7-Zip and Windows Explorer when I open it. Any idea why?

**Comment by riverar** [comment]
> @riverar your repro zip crashes 7-Zip and Windows Explorer when I open it. Any idea why?

Probably the OS, here's a GitHub repo instead. https://github.com/riverar/3096bc50ded7

> Also, you say it includes "wapproj" but the zip itself is named for "waproj" (only one 'p'). It turns out from what I understand, both of those are real and distinct project types. Which one are you struggling with?

Windows Application Packaging Project (wapproj).

I posted a workaround in https://github.com/microsoft/CsWin32/issues/560#issuecomment-2155486416 so if you want to keep this issue distinct for **non**-wapproj issues, happy to move the discussion there.

**Comment by AArnott** [comment]
> if you want to keep this issue distinct for non-wapproj issues, happy to move the discussion there.

Yes, please.

**Comment by jevansaks** [comment]
Are folks still running into issues with this? I tried the WPF publishing repro at the top of this issue and it publishes today. I am using .NET 9 SDK for this, and we know that there have been issues with the XamlPreCompile target not passing in all the same necessary parameters as the normal C# compile target. I suspect something in that vicinity was fixed in the .NET SDK.

I'll close this for now, reopen if you still see issues.

**Comment by riverar** [comment]
I don't have permission to re-open, but it's still broken https://github.com/microsoft/CsWin32/issues/1188#issuecomment-2158994825. Tested with `10.0.100-rc.2`. (But that's the waproj scenario.)

**Comment by riverar** [comment]
The non-waproj scenario seems similarly broken.

```
2>S:\WpfCsWin32PublishApp\WpfCsWin32PublishApp\MainWindow.xaml.cs(4,7): Error CS0246: The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
2>S:\WpfCsWin32PublishApp\WpfCsWin32PublishApp\MainWindow.xaml.cs(5,7): Error CS0246: The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
2>S:\WpfCsWin32PublishApp\WpfCsWin32PublishApp\MainWindow.xaml.cs(34,37): Error CS0246: The type or namespace name 'HWND' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by riverar** [comment]
@jevansaks Maybe we punt this to an issue in VSCommunity and accept my workaround as the only solution going forward. I don't see any of this getting fixed any time soon (if ever). Doesn't seem fair to put this on CsWin32.

**Comment by jevansaks** [comment]
Oh I see this is ok from the command line but fails when publishing in VS. I can see from the binlogs that in VS there's a second invocation of CoreCompile from the target GenerateTemporaryTargetAssembly. Looks like VS is doing a "build" and then "publish" as opposed to "dotnet publish" which is doing publish, which depends on "build".

<img width="838" height="471" alt="Image" src="https://github.com/user-attachments/assets/cfbe4e41-6e0a-4ef5-9d14-df0387527eb4" />

Something about that second invocation of "publish" is not skipping some of the first-time work that the "build" target already did.

So yes I agree this is likely caused by some VS oddities but I don't know why cswin32's source generator specifically isn't running in this scenario.

I would encourage someone blocked on this to file an issue on DevCommunity and link it back here.

**Comment by jevansaks** [comment]
One more clue: The 3rd invocation of Csc does not pass AdditionalFiles to Csc, so cswin32 doesn't get the NativeMethods.txt and does nothing. Looks like the project that GenerateTemporaryTargetAssembly creates is not getting evaluated properly, so the cswin32.props which would normally include NativeMEthods.txt in AdditionalFiles is not getting run and that item group is empty.

Definitely smells like a .NET SDK bug.

**Comment by jevansaks** [comment]
I opened https://github.com/dotnet/sdk/issues/51474.
